# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3721dd5f8b4c827de011f55b985fd40c373b658e9d1231bccb8bda41c0f4da5c4c76ab81b457ae036f3919c245a59670cfdc167e164cc908790aaf4af980bf9d

test:
  secret_key_base: 86f5738a20228d8181bad51301d3f5af2de32aeb1f45c0bc8adb7230a823cccfac5ee2e2669776b14b80defd7df6d9ba728b7ffa039a38381bd847ef1a3b3698

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
